name: "Release Options"
description: "Print the release options for the project"
author: "Emily Lambrou"
branding:
  icon: 'notification'
  color: 'green'
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  gh_token:
    description: "GitHub Personal Access Token"
    required: true
  project_number:
    description: "The Project Number"
    required: true 
  project_title:
    description: "The Project Title"
    required: true
  duedate_field_name:
    description: "The field name of the due date"
    required: true
    default: 'Due Date'
  enterprise_github:
    description: "Determines if the GitHub is the enterprise ot not (True,False)"
    required: false
    default: 'False'
  repository_owner_type:
    description: "The type of the repository owner (organization, user)"
    required: true
    default: 'user'
  dry_run:
    description: "DryRun Mode (True, False)"
    required: false
    default: 'False'
